# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wedewde
service: top-api-aws

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-north-1'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-offline
  - serverless-jetpack
